ReturnOrderPortal/Controllers/ComponentProcessingController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using ReturnOrderPortal.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Text.Json;
using System.Threading.Tasks;

namespace ReturnOrderPortal.Controllers
{
    public class ComponentProcessingController : Controller
    {
        private readonly HttpClient client = null;
        private string gatewayUrl = "";
        //private ProcessResponse processResponse= new ProcessResponse();

        public ComponentProcessingController(HttpClient client, IConfiguration config)
        {
            this.client = client;
            gatewayUrl = config.GetValue<string>("AppSettings:GatewayComponent");
        }

        [HttpGet]
        public IActionResult CreateProcessRequest()
        {
            var obj = SessionHelper.GetObject<UserRequest>(HttpContext.Session, "CurrentUser");
            if (obj == null)
            {
                return RedirectToAction("Index","Authentication");
            }
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CreateProcessRequest(ProcessRequest processRequest)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    string stringData = JsonSerializer.Serialize(processRequest);
                    var contentData = new StringContent(stringData, System.Text.Encoding.UTF8, "application/json");
                    HttpResponseMessage response = await client.PostAsync($"{gatewayUrl}/ProcessDetails", contentData);

                    if (response.IsSuccessStatusCode)
                    {
                        ViewBag.Message = "Process Requested successfully";
                        TempData["CreditCardNumber"] = processRequest.CreditCardNumber;

                        string stringDataResponse = await response.Content.ReadAsStringAsync();
                        var options = new JsonSerializerOptions
                        {
                            PropertyNameCaseInsensitive = true
                        };

                        ProcessResponse processResponse = JsonSerializer.Deserialize<ProcessResponse>(stringDataResponse, options);

                        TempData["processingCharge"] = processResponse.ProcessingCharge.ToString();
                        TempData["packageDeliveryCharge"] = processResponse.PackageAndDeliveryCharge.ToString();
                        TempData["DateOfDelivery"] = processResponse.DateOfDelivery.ToString();
                        TempData["processRequestId"] = processResponse.ProcessRequestId.ToString();

                        return RedirectToAction("CompleteProcess", processResponse);
                    }
                    else if (response.StatusCode == System.Net.HttpStatusCode.BadRequest)
                    {
                        ViewBag.Message = "Credit Card Details Were Wrong  Or You Have Insuficient Balance";
                        return View("CustomError");
                    }
                    else if (response.StatusCode == System.Net.HttpStatusCode.NotFound)
                    {
                        ViewBag.Message = "No Account found for this Account ID";
                        return View("CustomError");
                    }
                    else if (response.StatusCode == System.Net.HttpStatusCode.InternalServerError)
                    {
                        ViewBag.Message = "500 Internal Server Error";
                        return View("CustomError");
                    }
                    else
                    {
                        ViewBag.Message = "Server Under Maintenance";
                        return View("CustomError");
                    }
                }
                catch (Exception e)
                {
                    ViewBag.Message = e.Message;
                    return View("CustomError");
                }
            }
            return View("SessionExpired");
        }

      [HttpGet]
      public IActionResult CompleteProcess(ProcessResponse processResponse)
      {
            var obj = SessionHelper.GetObject<UserRequest>(HttpContext.Session, "CurrentUser");
            if (obj == null)
            {
                return RedirectToAction("Index", "Authentication");
            }
            return View(processResponse);
      }

      [HttpPost]
      [ValidateAntiForgeryToken]
      [ActionName("CompleteProcess")]
      public async Task<IActionResult> CompleteProcessConfirm(ProcessResponse processResponse)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    processResponse.ProcessRequestId = Int32.Parse(TempData["processRequestId"].ToString());
                    processResponse.PackageAndDeliveryCharge = Decimal.Parse(TempData["packageDeliveryCharge"].ToString());
                    processResponse.ProcessingCharge = Decimal.Parse(TempData["processingCharge"].ToString());
                    processResponse.DateOfDelivery = DateTime.Parse(TempData["DateOfDelivery"].ToString());

                    string stringData = JsonSerializer.Serialize(processResponse);
                    var contentData = new StringContent(stringData, System.Text.Encoding.UTF8, "application/json");
                    string creditCardNumber = TempData["CreditCardNumber"].ToString();

                    HttpResponseMessage response = await client.PostAsync($"{gatewayUrl}/CompleteProcessing/{processResponse.ProcessRequestId}/{creditCardNumber}/{processResponse.ProcessingCharge}", contentData);

                    if (response.IsSuccessStatusCode)
                    {
                        return View("Congratulations");
                    }
                    else if (response.StatusCode == System.Net.HttpStatusCode.BadRequest)
                    {
                        ViewBag.Message = "Bad Request Error, Check your card details";
                        return View("CustomError");
                    }
                    else if (response.StatusCode == System.Net.HttpStatusCode.NotFound)
                    {
                        ViewBag.Message = "No Account found for this Account ID";
                        return View("CustomError");
                    }
                    else if (response.StatusCode == System.Net.HttpStatusCode.InternalServerError)
                    {
                        ViewBag.Message = "500 Internal Server Error";
                        return View("CustomError");
                    }
                    else
                    {
                        ViewBag.Message = "Server Under Maintenance";
                        return View("CustomError");
                    }
                }
                catch (Exception e)
                {
                    ViewBag.Message = e.Message;
                    return View("CustomError");
                }
            }

            return View("SessionExpired");
        }
    }
}

ReturnOrderPortal/Views/Shared/CustomError.cshtml
@{
    ViewData["Title"] = "CustomError";
}

<h1>@ViewBag.Message</h1>
@Html.ActionLink("go back", "HomePage", "Authentication");

ReturnOrderPortal/Views/Shared/Invalid.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link href="https://fonts.googleapis.com/css?family=Poppins:100,200,300,400,500,600,700,800,900&display=swap" rel="stylesheet">

    <!-- Bootstrap core CSS -->
    <link href="vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">

    <link rel="stylesheet" href="~/assets/css/fontawesome.css">
    <link rel="stylesheet" href="~/assets/css/templatemo-sixteen.css">
    <link rel="stylesheet" href="~/assets/css/owl.css">

</head>

<body>
    <br />
    <br />
    <br />
    <div class="container">
        <h1>Invalid credentials.</h1>
        <a asp-action="Logout">return to login page</a>
    </div>

    <script src="~/vendor/jquery/jquery.min.js"></script>
    <script src="~/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>


    <!-- Additional Scripts -->
    <script src="~/assets/js/custom.js"></script>
    <script src="~/assets/js/owl.js"></script>
    <script src="~/assets/js/slick.js"></script>
    <script src="~/assets/js/isotope.js"></script>

</body>

ReturnOrderPortal/Views/Shared/SessionExpired.cshtml
@{
    ViewData["Title"] = "View";
    Layout = "~/Views/Shared/_Layout.cshtml";
}




<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link href="https://fonts.googleapis.com/css?family=Poppins:100,200,300,400,500,600,700,800,900&display=swap" rel="stylesheet">

    <!-- Bootstrap core CSS -->
    <link href="vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">

    <link rel="stylesheet" href="~/assets/css/fontawesome.css">
    <link rel="stylesheet" href="~/assets/css/templatemo-sixteen.css">
    <link rel="stylesheet" href="~/assets/css/owl.css">

</head>

<body>
    <br />
    <br />
    <br />
    <div class="container">
        <h1>Session Expired</h1>
        <a asp-action="Logout" asp-controller="Authentication">Sign in</a>
    </div>

    <script src="~/vendor/jquery/jquery.min.js"></script>
    <script src="~/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>


    <!-- Additional Scripts -->
    <script src="~/assets/js/custom.js"></script>
    <script src="~/assets/js/owl.js"></script>
    <script src="~/assets/js/slick.js"></script>
    <script src="~/assets/js/isotope.js"></script>

</body>

ReturnOrderPortal/Views/Shared/SomethingWentWrong.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>


@{
    ViewData["Title"] = "SomethingWentWrong";
}

<head>

    <!-- Google font -->
    <link href="https://fonts.googleapis.com/css?family=Montserrat:200,400,700" rel="stylesheet">

    <!-- Custom stlylesheet -->
    <link type="text/css" rel="stylesheet" href="~/css/SomethingWentWrong.css" />

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
          <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
          <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
        <![endif]-->

</head>

<body>

    <div id="notfound">
        <div class="notfound">
            <div class="notfound-404">
                <h1>Oops!</h1>
                <h2>404 - The Page can't be found</h2>
            </div>

            <form  asp-action="HomePage" asp-controller="Authentication">
                <button type="submit" class="btn btn-danger">Take me Home</button>
            </form>
        </div>
    </div>

</body>

ReturnOrderPortal/Views/Shared/UnAuthorized.cshtml
@{
    ViewData["Title"] = "View1";
    Layout = "~/Views/Shared/_Layout.cshtml";
}



<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link href="https://fonts.googleapis.com/css?family=Poppins:100,200,300,400,500,600,700,800,900&display=swap" rel="stylesheet">

    <!-- Bootstrap core CSS -->
    <link href="vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">

    <link rel="stylesheet" href="~/assets/css/fontawesome.css">
    <link rel="stylesheet" href="~/assets/css/templatemo-sixteen.css">
    <link rel="stylesheet" href="~/assets/css/owl.css">

</head>

<body>
    <br />
    <br />
    <br />
    <div class="container">
        <h1>Unauthorised Access</h1>
        <a asp-action="Logout" asp-controller="Authentication">click here</a>
    </div>

    <script src="~/vendor/jquery/jquery.min.js"></script>
    <script src="~/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>


    <!-- Additional Scripts -->
    <script src="~/assets/js/custom.js"></script>
    <script src="~/assets/js/owl.js"></script>
    <script src="~/assets/js/slick.js"></script>
    <script src="~/assets/js/isotope.js"></script>

</body>

ReturnOrderPortal/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Return Me</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Authentication" asp-action="HomePage">Return Me</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="AboutUs">About us</a>
                        </li>
                        @{ var x = Context.Session.GetObject<UserRequest>("CurrentUser");}
                        @if (x == null)
                        {

                            <li class="nav-item" style="margin-left:45em;">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Authentication" asp-action="Index">Login</a>
                            </li>


                        }
                        else
                        {
                            <li class="nav-item" style="margin-left:35em;">
                                <a class="nav-link text-dark" asp-area="" asp-controller="ComponentProcessing" asp-action="CreateProcessRequest">Replace/Return</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Authentication" asp-action="Logout">Logout</a>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>


    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>